Repository olinlibrary/ABE, pull requests merged in 2018-04, with the labels that each got.

#119 Improve setup documentation
  README.md
  abe/mongo_config_sample.py
Labels: enhancement

#127 Refactor environment and upgrade to Gunicorn
  .env.template
  .travis.yml
  Pipfile
  Pipfile.lock
  ProcfileHoncho
  README.md
  guniconf.py
  requirements.txt
  run.py
  runtime.txt
Labels: devops

#179 Add some test case stubs for ics and subscriptions
  abe/helper_functions/ics_helpers.py
  tests/test_ics_helpers.py
  tests/test_recurrences.py
  tests/test_subscription_resources.py
Labels: internal
